# Generated by Django 4.2.1 on 2024-02-09 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentmodel',
            old_name='creates',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='creates',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='creates',
            new_name='created',
        ),
        migrations.AddField(
            model_name='comentmodel',
            name='userComment',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='name',
            field=models.CharField(default='userName', max_length=100),
        ),
        migrations.AddField(
            model_name='profil',
            name='userEmail',
            field=models.CharField(default='email..', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentmodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.postmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='postImages/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
