# Generated by Django 4.2.1 on 2024-02-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_creates_comentmodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentmodel',
            name='userComment',
        ),
        migrations.AddField(
            model_name='comentmodel',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profil'),
        ),
    ]
